Add colors to assets catalog
arctouch-raphaelmartin/arc-money pull request #10
Opened 2024-10-23 13:00 UTC by arctouch-jamilebastos

# ArcMoney Pull Request

## Issue
This Pull Request closes #1

## What changed?

* Added color to assets catalog

## Testing

`ArcMoneyColors.secondary`

## Evidence

<img width="183" alt="Screenshot 2024-10-23 at 09 59 16" src="https://github.com/user-attachments/assets/2040e845-2424-4366-8ea4-dc821eba571a">

2024-10-30 13:37 UTC, arctouch-raphaelmartin requested changes

2024-10-30 13:37 UTC, arctouch-raphaelmartin commented on ArcMoney/Utils/Colors.swift
> +//    static let backdrop = Color("Backdrop")
I don't think it's needed to have this commented code here. If we add more colors to the assets catalog we'll not remember to update this comment section

2024-10-30 13:42 UTC, arctouch-raphaelmartin commented on ArcMoney.xcodeproj/project.pbxproj
> +/* End PBXFileSystemSynchronizedRootGroup section */
Apparently in XCode 16 using folder is the default, but since the project is already using Groups, I'd stick to Groups

2024-11-21 13:05 UTC, arctouch-jamilebastos commented on ArcMoney/Utils/Colors.swift
> +//    static let backdrop = Color("Backdrop")
You're right, I've removed

2024-11-21 13:05 UTC, arctouch-jamilebastos commented on ArcMoney/Utils/Colors.swift
> +enum ArcMoneyColors {
After our conversation, I've changed it to `Color`

2024-11-21 13:42 UTC, arctouch-raphaelmartin approved these changes

2024-11-21 13:42 UTC, merged