Create all label components
arctouch-raphaelmartin/arc-money pull request #15
Opened 2024-11-25 14:18 UTC by arctouch-jamilebastos

# ArcMoney Pull Request

## Issue
This Pull Request closes #2 

## What changed?

* Add a component for each label following design on figma

## Testing

* Open the preview on `Labels.swift`

## Evidence

<img width="549" alt="Screenshot 2024-11-25 at 11 06 40" src="https://github.com/user-attachments/assets/3f2ccb8d-79a2-4ed7-9974-28a05035065d">

2024-11-25 22:24 UTC, arctouch-matheusvaccaro commented on ArcMoney/Components/Labels.swift
> +}
**Suggestion**

Customizing the label sizes could be a nice opportunity for us to experiment with those `ViewModifiers` that @arctouch-raphaelmartin mentioned in one of our Syncs before the vacations.

I'll make a post in our channel to showcase the sugegstion

2024-11-26 20:07 UTC, arctouch-raphaelmartin commented on ArcMoney/Components/Labels.swift
> +}
I agree, that's a great idea!

2024-11-26 20:08 UTC, arctouch-raphaelmartin approved these changes
Besides the @arctouch-matheusvaccaro 's suggestion, everything looks good

2024-12-12 13:46 UTC, arctouch-raphaelmartin requested changes

2024-12-12 13:46 UTC, arctouch-raphaelmartin commented on ArcMoney/Components/Labels.swift
> +    func customStyle(_ style: TextStyle) -> some View {
Since the extension is in the `View` type, but it's meant to be used with texts only, what about renaning the function to `textStyle` instead of `customStyle`?

2024-12-12 13:47 UTC, arctouch-raphaelmartin commented
@arctouch-jamilebastos You have some conflicts with the main branch, please solve them locally before we can merge, thanks!

2024-12-12 13:57 UTC, arctouch-jamilebastos commented on ArcMoney/Components/Labels.swift
> +    func customStyle(_ style: TextStyle) -> some View {
Done ✅

2024-12-12 14:01 UTC, arctouch-raphaelmartin approved these changes

2024-12-12 14:25 UTC, merged