[Issue-18] Create BackgroundedIcon Component
arctouch-raphaelmartin/arc-money pull request #19
Opened 2024-11-26 04:36 UTC by arctouch-matheusvaccaro

# ArcMoney Pull Request

## Issue
This Pull Request closes #18

## What changed?
This PR adds a couple new files to the project:
- `ArcMoneySpacing`: An enum containing common spacing values to be used by the components of the Design System.
- `ArcMoneyCornerRadius`: An enum containing common corner radii to be used by the components of the Design System.
- `View+Extensions`: An utility extension file to hold modified versions of the `padding(_: CGFloat)` and `cornerRadius(_: CGFloat)` methods so that they can be used directly with `ArcMoneySpacing` and `ArcMoneyCornerRadius`.
- `BackgroundedImageView`: A View Component that builds on top of all other classes we created for the Design System so we can easily create Icons that have a rounded background color.

> IMPORTANT: This PR depends on #13 

## Testing
`BackgroundedIconView` should be able to be used inside any SwiftUI view, like the preview below:

![Screenshot 2024-11-26 at 1 26 20 AM](https://github.com/user-attachments/assets/33dc0576-8393-4974-8c48-23b9e2d395aa)

## Evidence
![Screenshot 2024-11-26 at 1 25 52 AM](https://github.com/user-attachments/assets/99e1913c-5276-48be-a226-e15123df336c)

2024-11-27 13:42 UTC, arctouch-raphaelmartin requested changes

2024-11-27 13:42 UTC, arctouch-raphaelmartin commented on ArcMoney/Utils/ArcMoneyCornerRadius.swift
> +    case fullCapsule
How did you define the need of having all these 13 cases at this enum? I'm not a big fan of creating these properties for "if I need anytime it's already there", because it's very possible that most of it will never be used.

I'd suggest creating the radius variations that you see in the design.

2024-11-27 13:42 UTC, arctouch-raphaelmartin commented on ArcMoney/Utils/ArcMoneyCornerRadius.swift
> +    var value: CGFloat {
can we make the enum inherits from `CGFloat` as the `ArcMoneySize` one?

2024-11-27 13:42 UTC, arctouch-raphaelmartin commented on ArcMoney/Utils/ArcMoneySpacing.swift
> +    case four = 64
Here I have the same concern about maybe having more values then needed. What you think?

2024-11-28 14:44 UTC, arctouch-raphaelmartin commented on ArcMoney/Extensions/View+Extensions.swift
> +            cornerRadius(radius.value)
As discussed in weekly sync, we agreed in changing this to a clipShape(RoundedRectangle)

2024-12-04 15:40 UTC, arctouch-matheusvaccaro commented on ArcMoney/Utils/ArcMoneyCornerRadius.swift
> +    var value: CGFloat {
Done!

[78f86c9](https://github.com/arctouch-raphaelmartin/arc-money/pull/19/commits/78f86c915a30f331fd202b66ace18b8dad0cc346) ✅

2024-12-04 15:44 UTC, arctouch-matheusvaccaro commented on ArcMoney/Extensions/View+Extensions.swift
> +            cornerRadius(radius.value)
Done!

[50cfe02](https://github.com/arctouch-raphaelmartin/arc-money/pull/19/commits/50cfe02356d89b5e626051c44527e9f0993780c1) ✅

2024-12-04 16:25 UTC, arctouch-matheusvaccaro commented on ArcMoney/Utils/ArcMoneySpacing.swift
> +    case four = 64
Removed spacings that I could not identify in the design

[dc86378](https://github.com/arctouch-raphaelmartin/arc-money/pull/19/commits/dc86378c1993c968b1e9f15936910495a3c508d8) ✅

2024-12-05 19:37 UTC, arctouch-raphaelmartin approved these changes
LGMT!

2024-12-11 13:53 UTC, arctouch-jamilebastos approved these changes

2024-12-12 15:37 UTC, merged